version: '3.8'

services:
  postgres:
    image: postgres
    container_name: customer-data-api-postgres
    environment:
      - POSTGRES_PASSWORD=customer-data-api
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - customer-data-api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-data-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8000:8000'
    expose:
      - 8000
    networks:
      - customer-data-api
    env_file:
      - cmd/.env

networks:
  customer-data-api:
    driver: bridge
